### ISSUE TITLE
Cant Find A group Id  called (meme_templates2)  

### ISSUE THREAD

**Issue by indrasenareddy91** [ahmeterenodaci/telegram-message-scraper#1]
While trying out the scraper I got no channel found message when I queried (meme_templates2) as the id of the channel. this group is a public group. I double verified the telegram id of that group.I also searched it from the app itself to know if the id is they provided in their bio is correct or not and the channel is found with that id. But while searching front the package it return no channel found msg. 
![Screenshot_2024-07-23-22-54-06-043-edit_org telegram messenger](https://github.com/user-attachments/assets/df6eb97c-e110-4251-b7c3-4510d10f9c82)

**Comment by ahmeterenodaci** [comment]
Hi, some channels are “marked” as containing sensitive materials (offensive, politics etc.). Because of this it does not show preview on web version. [Here is your channel.](https://t.me/meme_templates2)

To get messages from a channel it needs to be open to public view. [Here is a public channel.](https://t.me/telegram)

**Comment by indrasenareddy91** [comment]
ok but is there any way that I can still scrape msgs from the channel?

**Comment by ahmeterenodaci** [comment]
As far as I know you can't
